# Generated by Django 3.1.3 on 2021-01-06 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subsriber',
            new_name='Subscriber',
        ),
    ]
