# Generated by Django 3.1.3 on 2021-01-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=11),
        ),
    ]
